server:
  port: 8080

external:
  rent-points:
    url: http://localhost:8082/geocommerce
  retail-points:
    url: http://localhost:8081/geocommerce
  population:
    url: http://localhost:8083/geocommerce
  nominatim:
    url: https://nominatim.openstreetmap.org

spring:
  application:
    name: geo-commerce-service

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics

  datasource:
    url: jdbc:postgresql://localhost:5432/geocommerce_db
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE